apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  labels:
    name: sample-pod
  annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "default-vault-injector-agent-role"
        vault.hashicorp.com/agent-inject-secret-credentials: "secret/data/default/test-secret"
spec:
  serviceAccountName: default-vault-injector-agent
  containers:
  - name: app
    image: "nginx:1.7.8"
    resources:
      limits:
        cpu: "0.5"
        memory: "512Mi"
      requests:
        cpu: "250m"
        memory: "50Mi"
